# https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary

name: adding-a-job-summary

on:
  workflow_dispatch:


jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
     - run: |
        echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
