name: emoji-notify
on: [workflow_dispatch, pull_request]
jobs:
  notify:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - run: echo "::notice title=cs:::warning:this warning emoji"
      - run: echo "::notice title=cs::⚠️ this warning emoji"
