name: Call a reusable workflow

on: workflow_dispatch

jobs:
  call-workflow-job1:
    uses: bxb100/action-test/.github/workflows/reusable-workflow-A.yml@main

  call-workflow-job2:
    runs-on: ubuntu-latest
    needs: call-workflow-job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}

  call-workflow-passing-data:
    uses: bxb100/action-test/.github/workflows/reusable-workflow-B.yml@main
    with:
      username: mona
    secrets:
      token: token-cs
