name: reusable-workflow-C

concurrency: 
  group: production
  cancel-in-progress: true

on:
  workflow_call:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy1
        # ...deployment-specific steps
        run: |
          sleep 1m;
          echo OK1
      - name: deploy2
        run: echo OK2
