name: stackoverflow-68759990-2

on:
  workflow_run:
    workflows: ["stackoverflow-68759990-1"]
    types:
      - completed

jobs:
    actions-tagger:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest
      steps: 
        - run: |
            echo 'second'
            echo "${{ toJSON(github.event.workflow_run) }}"
