name: Using resuing workflow way

on:
  pull_request:
    branches: [ main ]

jobs:
  first:
    name: pretend the First workflow
    uses: bxb100/action-test/.github/workflows/reusable-workflow-A.yml@main
   
  second:
    name: pretend the Second workflow
    needs: first
    uses: bxb100/action-test/.github/workflows/reusable-workflow-C.yml@main
